name: "webapi: Docker Image CI"

on:
  push:
    branches: [ "main" ]
    tags: ['v*']
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      context: ./apps
      dockerfile: ./webapi/Dockerfile
      push: ${{ startsWith(github.ref, 'refs/tags/v') }}
      image: gldraphael/scale-webapi
    permissions:
      contents: read
      packages: write
